version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - ./mongo_volume:/data/db
    ports:
      - 27018:27017
  jupyter:
    build: ./jupyter
    command: jupyter notebook --ip=0.0.0.0 --allow-root
    volumes:
      - ./jupyter:/usr/src/app
    environment:
      - VIRTUAL_HOST
      - VIRTUAL_PORT
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
    ports:
      - 8890:8888
    depends_on:
      - mongo
  flask_app:
    build: ./flask
    command: flask run --host 0.0.0.0
    environment:
      - FLASK_APP=flask_app.py
    volumes:
      - ./flask:/usr/src/app
    ports:
      - 5051:5000
    depends_on:
      - mongo
# https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion
networks:
  default:
    external:
      name: webproxy
