version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
  jupyter:
    build: ./jupyter
    command: jupyter notebook --ip=0.0.0.0 --allow-root
    ports:
      - 8890:8888
    volumes:
      - ./jupyter:/usr/src/app
    depends_on:
      - mongo
