version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - PGDATA
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
  flask_app:
    build: .
    command: flask run --host 0.0.0.0
    environment:
      - FLASK_APP=flask_app.py
      - VIRTUAL_HOST
      - VIRTUAL_PORT
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - .:/usr/src/app
    ports:
      - "5050:5000"
    depends_on:
      - db
# https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion
networks:
  default:
    external:
      name: webproxy
