version: '3'
services:
  db:
    image: postgres
  flask_app:
    build: .
    command: flask run --host 0.0.0.0
    environment:
      - FLASK_APP=flask_app.py
      - 
    volumes:
      - .:/usr/src/app
    ports:
      - "5050:5000"
    depends_on:
      - db
